# Flag whether all network devices are controlled by this role
#
# If true, all additional scripts are deleted
network_manage_devices: yes

# Allow the network to restart
#
# This is only triggered, when the all interface file was changed
network_allow_service_restart: no

network_need_restart_immediately: false

network_vmxnet3_workaround: yes
network_vmxnet3_udev_location: /etc/udev/rules.d/99-vmxnet3-workaround.rules
network_vmxnet3_script_location: /usr/local/bin/transform_name

# How should changed interfaces be treated?
#
# Options:
#   service - restart the network service for the interface
#   interface - down & up the interface
#   nothing - do nothing
#   * - undefined behavior
network_restart_method: service

network_iproute2_configure: no

#network_iproute2_tables:
#  - id: 10
#    name: vlan10

network_iproute2_tables:

# List of all network interface configurations
#
# For ipv6 you want to add an additional inet6 entry
network_interfaces:
  - device: eth0
    # auto & allow are only used for the first device entry
    auto: true # enable on boot (default)
    allow: ['hotplug'] # array of allow-[stanzas] eg. allow-hotplug

    family: inet # network type eg. inet | inet6 (default)
    method: manual
    # examples for method 'static'
    #description: 'a user description'
    #address: 192.168.1.11
    #network: 192.168.1.0
    #netmask: 193.168.1.255
    #broadcast: 192.168.1.255
    #gateway: 192.168.1.1

    # optional dns settings
    #nameservers: ['8.8.8.8']
    #dns_search: "domain.net" # appended dns search string

    # optional additional subnets/ips
    #subnets: ['192.168.123.0/24', '192.168.124.11/32']

    bridge: {} # optional bridge parameters
    #  ports:
    #  stp:
    #  fd:
    #  maxwait:
    #  waitport:

    # optional vlan settings
    vlan: {}
    #  raw-device: 'eth0'

    # inline hook scripts
    pre-up: [] # pre-up script lines
    up: [] # up script lines
    post-up: [] # post-up script lines (alias for up)
    pre-down: [] # pre-down script lines (alias for down)
    down: [] # down script lines
    post-down: [] # post-down script lines
