- hosts: "{{ grp | default('all') }}"
  gather_facts: true
  become: true
  vars: 
    dnsdist_version: "1.8.0"
    dnsdist_web_pass: "DnsDinst"
    dnsdist_web_APIkey: "DnsDinst"
    namesrv: "dnsdist4"
    ifcfg: 
      - 'ens33'
      - 'ens160'
      - 'ens192'
  roles:
#    - zabbix_agent2-redos
    - nftables
    - dnsdist

