---
# defaults file
network_interfaces:
  - device: ens33
    address: "IP"

dnsdist_acl:
  - "172.17.3.5"
  - "172.17.3.6"

srv_count: "0"
dnsdist_PacketCache_size: "1000000"
dnsdist_PacketCache_TTLx: "3600"

dnsdist_views:
  - views:
    pool: "Pool(view)_name"
    PacketCache: "{{ dnsdist_PacketCache_size }}"
    node:
      - name: "server_name"
        ip: "172.17.3.29:5300"
    client_ip:
      - "5300"

dnsdist_action:
  - "AndRule({QTypeRule(DNSQType.ANY), TCPRule(false)}), DropAction()"
  - "MaxQPSIPRule(200,32,64,100), DelayAction(500)"

dnsdist_max_check_failures: "1"

dnsdist_GlobalConfig:
  - setVerboseHealthChecks(true)
  - setMaxTCPClientThreads(100) # def:10
  - setMaxTCPQueuedConnections(10000) # def: 1000
  - setMaxUDPOutstanding(65535) # def:65535
  - setTCPUseSinglePipe(true)
  #- setCacheCleaningDelay(30)
  #- setCacheCleaningPercentage(20)
  #- setStaleCacheEntriesTTL(600)

