---
# The name of the dnsdist package
default_dnsdist_package_name: dnsdist

# The name of the dnsdist debug package
default_dnsdist_debug_symbols_package_name: "{% if ansible_distribution == 'Debian' and ansible_distribution_version | int < 9 or ansible_distribution == 'Ubuntu'\
  \ and ansible_distribution_version <= '16.04' %}dnsdist-dbg{% else %}dnsdist-dbgsym{% endif %}"

# The default location of the config file
default_dnsdist_config_location: /etc/dnsdist/dnsdist.conf

# The default owner/group of the process and files: 1.5 and beyond
default_dnsdist_owner: _dnsdist
default_dnsdist_group: _dnsdist

# The default owner/group of the process and files: 1.4 and earlier
default_dnsdist_owner_pre15: root
default_dnsdist_group_pre15: root
