---
- include: vmxnet3_workaround.yml
  when: network_vmxnet3_workaround

- include: iproute2.yml
  when: network_iproute2_configure|bool

#- name: ensure basic networking tools are installed
#  apt:
#    pkg: "{{ item }}"
#    state: present
#  with_items:
#    - vlan
#    - ifenslave

- name: ensure basic networking tools are installed
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - vlan
      - ifenslave

- include: all_interfaces.yml
  when: network_interfaces|bool == false

- name: configurations
  template:
    src: device.j2
    dest: "{{ network_interface_path }}/device-{{ item.0 }}"
  with_items:
    - "{{network_interfaces | default([]) | groupby('device') }}"
  register: network_configuration_result
  notify:
    - network restart interface service
    - network restart interface command

- include: manage_devices.yml
  when: network_manage_devices|bool

- name: Force run handlers if network_need_restart_immediately is yes
  include_tasks: restart_now.yml
  when: network_need_restart_immediately|bool
