---
- name: Копируем скрипт автозапуска службы в /usr/local/lib/systemd/system/dnsdist.service
  copy:
    src: dnsdist.service
    dest: /usr/lib/systemd/system/dnsdist.service
    owner: root
    group: root
    mode: 0644
  notify: restart dnsdist services

#- name: Create symlink /lib/systemd/system/dnsdist.service
#  file:
#    src: /usr/local/lib/systemd/system/dnsdist.service
#    dest: /etc/systemd/system/multi-user.target.wants/dnsdist.service
#    state: link
#    remote_src: 'True'
#  notify: restart dnsdist services

- name: Для установки службы рестартуем systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes

- name: Enable dnsdist.service
  service:
    name: dnsdist.service
    enabled: yes

- name: Add the group 'dnsdist'
  group:
    name: dnsdist
    state: present

- name: Add the user 'dnsdist'
  user:
    name: dnsdist
    group: dnsdist
    shell: /bin/false
    home: /nonexistent
    append: yes

- name: Create directory /etc/dnsdist
  file:
    path: /etc/dnsdist
    state: directory
    mode: 0755
    owner: root
    group: dnsdist

- name: Copy console.conf to /etc/dnsdist/
  template:
    src: console.conf.j2
    dest: /etc/dnsdist/console.conf
    owner: root
    group: dnsdist
    mode: 0644

- name: Create dnsdist.conf
  template:
    src: dnsdist.conf.j2
#    src: dnsdist.conf
    dest: /etc/dnsdist/dnsdist.conf
    owner: root
    group: dnsdist
    mode: 0644
  notify: restart dnsdist services

- name: Create bash profile.d file srvadm_aliases_dnsdist.sh with aliases
  copy:
    src: srvadm_aliases_dnsdist.sh
    dest: /etc/profile.d/srvadm_aliases_dnsdist.sh
    owner: root
    group: root
    mode: 0644

- name: Copy dnsdist.py to /usr/local/bin/
  copy:
    src: dnsdist.py
    dest: /usr//bin/dnsdist.py
    owner: root
    group: root
    mode: 0755

- name: Copy query.acl to /etc/dnsdist
  copy:
    src: acl/query.acl
    dest: /etc/dnsdist/query.acl
    owner: root
    group: dnsdist
    mode: 0644

#Пока закомментировано
#- name: Copy srv_adm_nf_conntrack.conf to /etc/zabbix/zabbix_agentd.d/
#  copy:
#    src: srv_adm_nf_conntrack.conf
#    dest: /etc/zabbix/zabbix_agentd.d/srv_adm_nf_conntrack.conf
#    owner: root
#    group: root
#    mode: 0644
#  notify: restart zabbix_agentd

- name: Copy dnsdist_rsyslog.conf /etc/rsyslog.d/dnsdist_rsyslog.conf
  copy:
    src: dnsdist_rsyslog.conf
    dest: /etc/rsyslog.d/dnsdist_rsyslog.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog

- name: Restart dnsdist
  service:
      name: dnsdist
      state: restarted

- name: Copy dnsdist_logrotate.conf
  copy:
    src: dnsdist_logrotate.conf
    dest: /etc/logrotate.d/dnsdist_logrotate.conf
    owner: root
    group: root
    mode: 0644


